env:
  MAVEN_ARGS: -V -B --no-transfer-progress -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  linux_bazel:
    name: Linux JDK ${{ matrix.java }} Bazel
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Mount bazel cache
      uses: actions/cache@v1
      with:
        key: bazel
        path: /home/runner/.cache/bazel
    - continue-on-error: true
      name: Install bazel
      run: "curl -LO \"https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64\"\
        \nmkdir -p \"${GITHUB_WORKSPACE}/bin/\"\nmv bazelisk-linux-amd64 \"${GITHUB_WORKSPACE}/bin/bazel\"\
        \nchmod +x \"${GITHUB_WORKSPACE}/bin/bazel\"          \n"
    - continue-on-error: true
      name: Test
      run: '"${GITHUB_WORKSPACE}/bin/bazel" test //...

        '
    - continue-on-error: true
      name: Build
      run: '"${GITHUB_WORKSPACE}/bin/bazel" build //...

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
  linux_gradle:
    name: Linux JDK ${{ matrix.java }} Gradle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test
      run: ./gradlew buildAll
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
  linux_maven:
    name: Linux JDK ${{ matrix.java }} Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test
      run: ./mvnw ${MAVEN_ARGS} -U clean verify
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
  mac_maven:
    name: Mac OS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      name: Test
      run: ./mvnw ${MAVEN_ARGS} -U clean verify
  windows_maven:
    name: Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      name: Test
      run: ./mvnw ${MAVEN_ARGS} -U clean verify
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
